# -*- mode: ruby -*-
# vi: set ft=ruby :

# Global vagrant variables
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

# Testbox variables
config.vm.define "testbox" do |app|
  app.vm.box = "jasonc/centos8"
  app.vm.hostname = "testbox"
  app.vm.network "private_network", ip: "10.23.45.10"
  app.vm.provision "shell", path: "install.sh"
end

# Kanboard variables
config.vm.define "kanboard" do |kanboard|
  kanboard.vm.box = "jasonc/centos8"
  kanboard.vm.hostname = "kanboard"
  kanboard.vm.network "private_network", ip: "10.23.45.25"
  kanboard.vm.provision "shell", path: "kanboard-install.sh"
  kanboard.vm.box_check_update = false
 end

 # Virtualbox variables for all boxes
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end

end
