# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define "kanboard" do |kanboard|
  kanboard.vm.box = "jasonc/centos8"
  kanboard.vm.hostname = "kanboard"
  kanboard.vm.network "private_network", ip: "10.23.45.25"
  kanboard.vm.provision "shell", path: "kanboard-install.sh"
  kanboard.vm.box_check_update = false
  end
  
end
