# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "jasonc/centos8"
  config.vm.hostname = "kanboard"
  
  config.vm.network "private_network", ip: "10.23.45.25"

  config.vm.provision "shell", path: "kanboard-install.sh"

  config.vm.box_check_update = false
 
end
