# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "jasonc/centos8"
  config.vm.hostname = "hesk"
  config.vm.netowrk "private_network", ip: "10.23.45.20"


end
