# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "jasonc/centos8"
  config.vm.hostname = "grafana"
  config.vm.network "private_network", ip: "10.23.45.40"
  # config.vm.provision "shell", path: "grafana-install.sh"
end
