# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "jasonc/centos8"
  config.vm.hostname = "phpmyadmin"
  config.vm.network "private_network", ip: "10.23.45.35"

  config.vm.box_check_update = false
  config.vm.provision "shell", path: "install.sh"

end
