# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "jasonc/centos8"
  config.vm.hostname = "syslog"
  config.vm.network "private_network", ip: "10.23.45.50"
  config.vm.provision "shell", path: "syslog-install.sh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end

end
